esphome:
  name: "closetlswitch"
  friendly_name: "Closet lights"

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf
    platform_version: "https://github.com/stintel/platform-espressif32#esp32-c6-test"
    version: 5.1.2

# Enable logging
logger:

wifi: # Your wifi logic
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: github://franciscoaleixo/NH-Devices@main
    refresh: 0s

nh_alcv5t24:
  id: closet_nh_alcv5t24
  switch_sensor_relationship: Direct # It can either be direct (sensor ON - lights ON), inverse (sensor ON - lights OFF) or none

switch:
  - platform: nh_alcv5t24_light_switch
    controller_id: closet_nh_alcv5t24
    name: "Switch"

binary_sensor:
  - platform: nh_alcv5t24_binary_sensor
    controller_id: closet_nh_alcv5t24
    name: "Sensor"
    sensor_pin:
      number: 1 #1 for GPIO6, 2 for GPIO7. Connector is 1-GND, 2-3.3V, 3-GPIO6, 4-GPIO7
      mode:
        pullup: true
    filters:
      - delayed_on_off: 300ms